CREATE TABLE `account_defaults` (
	`id` varchar(20) NOT NULL DEFAULT 'default',
	`company_name` text,
	`company_domain` text,
	`address` text,
	`address2` text,
	`city` text,
	`state` text,
	`zip` text,
	`country` text,
	`bank_name` text,
	`bank_routing_number` text,
	`bank_swift_code` text,
	`bank_account_number` text,
	`billing_contact_email` text,
	`bank_address` text,
	`bank_address2` text,
	`bank_city` text,
	`bank_state` text,
	`bank_zip` text,
	`bank_country` text,
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `account_defaults_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companies` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`a_empresa_possui_esteira_ci_cd_construida_` text,
	`about_us` text,
	`address` text,
	`address2` text,
	`annualrevenue` decimal(20,6),
	`association_type` text,
	`city` text,
	`closedate` datetime,
	`controller__company_billing_process` text,
	`controller_company_owner_name` text,
	`controller_deal_id` decimal(20,6),
	`controller_last_customer_id` text,
	`controller_lead_process` text,
	`controller_partner_days_check_invoice_and_deals` text,
	`controller_partner_distributor` text,
	`controller_partner_id` text,
	`controller_resale_company` text,
	`controller_rotation_type` text,
	`country` text,
	`createdate` datetime,
	`days_to_close` decimal(20,6),
	`days_without_new_deals` decimal(20,6),
	`days_without_new_invoices` decimal(20,6),
	`description` text,
	`dessas_aplicacoes__quantas_sao_microservicos_` text,
	`domain` text,
	`engagements_last_meeting_booked` datetime,
	`engagements_last_meeting_booked_campaign` text,
	`engagements_last_meeting_booked_medium` text,
	`engagements_last_meeting_booked_source` text,
	`facebook_company_page` text,
	`facebookfans` decimal(20,6),
	`first_contact_createdate` datetime,
	`first_contact_createdate_timestamp_earliest_value_78b50eea` datetime,
	`first_conversion_date` datetime,
	`first_conversion_event_name` text,
	`first_deal_created_date` datetime,
	`founded_year` text,
	`googleplus_page` text,
	`hs_additional_domains` text,
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_analytics_first_timestamp` datetime,
	`hs_analytics_first_touch_converting_campaign` text,
	`hs_analytics_first_visit_timestamp` datetime,
	`hs_analytics_last_timestamp` datetime,
	`hs_analytics_last_timestamp_timestamp_latest_value_4e16365a` datetime,
	`hs_analytics_last_touch_converting_campaign` text,
	`hs_analytics_last_touch_converting_campaign_timestamp_la_e6867c` datetime,
	`hs_analytics_last_visit_timestamp` datetime,
	`hs_analytics_last_visit_timestamp_timestamp_latest_value_75d1e3` datetime,
	`hs_analytics_latest_source` text,
	`hs_analytics_latest_source_data_1` text,
	`hs_analytics_latest_source_data_2` text,
	`hs_analytics_latest_source_timestamp` datetime,
	`hs_analytics_num_page_views` decimal(20,6),
	`hs_analytics_num_page_views_cardinality_sum_e46e85b0` decimal(20,6),
	`hs_analytics_num_visits` decimal(20,6),
	`hs_analytics_num_visits_cardinality_sum_53d952a6` decimal(20,6),
	`hs_analytics_source` text,
	`hs_analytics_source_data_1` text,
	`hs_analytics_source_data_2` text,
	`hs_annual_revenue_currency_code` text,
	`hs_avatar_filemanager_key` text,
	`hs_calculated_phone_number` text,
	`hs_count_intent_signals_created_last_14_days` decimal(20,6),
	`hs_count_intent_signals_created_last_30_days` decimal(20,6),
	`hs_count_intent_signals_created_last_7_days` decimal(20,6),
	`hs_country_code` text,
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_csm_sentiment` text,
	`hs_current_customer` text,
	`hs_customer_success_ticket_sentiment` decimal(20,6),
	`hs_date_entered_123317274` datetime,
	`hs_date_entered_1334400296` datetime,
	`hs_date_entered_1334454586` datetime,
	`hs_date_entered_48119601` datetime,
	`hs_date_entered_customer` datetime,
	`hs_date_entered_evangelist` datetime,
	`hs_date_entered_lead` datetime,
	`hs_date_entered_marketingqualifiedlead` datetime,
	`hs_date_entered_opportunity` datetime,
	`hs_date_entered_other` datetime,
	`hs_date_entered_salesqualifiedlead` datetime,
	`hs_date_entered_subscriber` datetime,
	`hs_date_exited_123317274` datetime,
	`hs_date_exited_1334400296` datetime,
	`hs_date_exited_1334454586` datetime,
	`hs_date_exited_48119601` datetime,
	`hs_date_exited_customer` datetime,
	`hs_date_exited_evangelist` datetime,
	`hs_date_exited_lead` datetime,
	`hs_date_exited_marketingqualifiedlead` datetime,
	`hs_date_exited_opportunity` datetime,
	`hs_date_exited_other` datetime,
	`hs_date_exited_salesqualifiedlead` datetime,
	`hs_date_exited_subscriber` datetime,
	`hs_domain_status` text,
	`hs_employee_range` text,
	`hs_excluded_from_cross_account_data_mirroring` boolean,
	`hs_geohash_1` text,
	`hs_geohash_2` text,
	`hs_geohash_3` text,
	`hs_geohash_4` text,
	`hs_geohash_5` text,
	`hs_geohash_6` text,
	`hs_gps_error` text,
	`hs_gps_latitude` text,
	`hs_gps_longitude` text,
	`hs_ideal_customer_profile` text,
	`hs_industry_group` text,
	`hs_inferred_domain` text,
	`hs_intent_page_views_last_30_days` decimal(20,6),
	`hs_intent_paid_up_to_date` date,
	`hs_intent_signals_enabled` boolean,
	`hs_intent_visitors_last_30_days` decimal(20,6),
	`hs_is_enriched` boolean,
	`hs_is_intent_monitored` boolean,
	`hs_is_target_account` boolean,
	`hs_keywords` text,
	`hs_last_booked_meeting_date` datetime,
	`hs_last_logged_call_date` datetime,
	`hs_last_logged_outgoing_email_date` datetime,
	`hs_last_metered_enrichment_timestamp` datetime,
	`hs_last_open_task_date` datetime,
	`hs_last_sales_activity_date` datetime,
	`hs_last_sales_activity_timestamp` datetime,
	`hs_last_sales_activity_type` text,
	`hs_lastmodifieddate` datetime,
	`hs_latest_createdate_of_active_subscriptions` datetime,
	`hs_latest_intent_signal_occurred_at` datetime,
	`hs_latest_intent_signal_timestamp` decimal(20,6),
	`hs_latest_meeting_activity` datetime,
	`hs_latest_prospecting_agent_monitoring_date` decimal(20,6),
	`hs_latest_suggested_contact_timestamp` decimal(20,6),
	`hs_latitude` decimal(20,6),
	`hs_lead_status` text,
	`hs_linkedin_handle` text,
	`hs_live_enrichment_deadline` datetime,
	`hs_logo_url` text,
	`hs_longitude` decimal(20,6),
	`hs_max_recommendation_score` decimal(20,6),
	`hs_merged_object_ids` text,
	`hs_most_recent_de_anonymized_visit` datetime,
	`hs_next_renewal_date` date,
	`hs_notes_last_activity` text,
	`hs_notes_next_activity` text,
	`hs_notes_next_activity_type` text,
	`hs_num_active_contracts` decimal(20,6),
	`hs_num_blockers` decimal(20,6),
	`hs_num_child_companies` decimal(20,6),
	`hs_num_contacts_with_buying_roles` decimal(20,6),
	`hs_num_decision_makers` decimal(20,6),
	`hs_num_open_deals` decimal(20,6),
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_owning_teams` text,
	`hs_paid_for_intent_signals` boolean,
	`hs_parent_company_id` decimal(20,6),
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_pipeline` text,
	`hs_plays` text,
	`hs_predictivecontactscore_v2` decimal(20,6),
	`hs_predictivecontactscore_v2_next_max_max_d4e58c1e` decimal(20,6),
	`hs_quick_context` text,
	`hs_read_only` boolean,
	`hs_reason_to_reach_out` text,
	`hs_recent_intent_signals` text,
	`hs_redirect_domain` text,
	`hs_redirect_url` text,
	`hs_research_agent_execution_id` text,
	`hs_research_agent_id` decimal(20,6),
	`hs_revenue_range` text,
	`hs_sales_email_last_replied` datetime,
	`hs_searchable_calculated_international_phone_number` text,
	`hs_searchable_calculated_phone_number` text,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_signals_summary` text,
	`hs_source_object_id` decimal(20,6),
	`hs_state_code` text,
	`hs_suggested_contact_count` decimal(20,6),
	`hs_target_account` text,
	`hs_target_account_probability` decimal(20,6),
	`hs_target_account_recommendation_snooze_time` datetime,
	`hs_target_account_recommendation_state` text,
	`hs_task_label` text,
	`hs_tax_id` text,
	`hs_time_in_123317274` decimal(20,6),
	`hs_time_in_1334400296` decimal(20,6),
	`hs_time_in_1334454586` decimal(20,6),
	`hs_time_in_48119601` decimal(20,6),
	`hs_time_in_customer` decimal(20,6),
	`hs_time_in_evangelist` decimal(20,6),
	`hs_time_in_lead` decimal(20,6),
	`hs_time_in_marketingqualifiedlead` decimal(20,6),
	`hs_time_in_opportunity` decimal(20,6),
	`hs_time_in_other` decimal(20,6),
	`hs_time_in_salesqualifiedlead` decimal(20,6),
	`hs_time_in_subscriber` decimal(20,6),
	`hs_total_deal_value` decimal(20,6),
	`hs_unique_creation_key` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_recipients` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_v2_cumulative_time_in_123317274` decimal(20,6),
	`hs_v2_cumulative_time_in_1334400296` decimal(20,6),
	`hs_v2_cumulative_time_in_1334454586` decimal(20,6),
	`hs_v2_cumulative_time_in_48119601` decimal(20,6),
	`hs_v2_cumulative_time_in_customer` decimal(20,6),
	`hs_v2_cumulative_time_in_evangelist` decimal(20,6),
	`hs_v2_cumulative_time_in_lead` decimal(20,6),
	`hs_v2_cumulative_time_in_marketingqualifiedlead` decimal(20,6),
	`hs_v2_cumulative_time_in_opportunity` decimal(20,6),
	`hs_v2_cumulative_time_in_other` decimal(20,6),
	`hs_v2_cumulative_time_in_salesqualifiedlead` decimal(20,6),
	`hs_v2_cumulative_time_in_subscriber` decimal(20,6),
	`hs_v2_date_entered_123317274` datetime,
	`hs_v2_date_entered_1334400296` datetime,
	`hs_v2_date_entered_1334454586` datetime,
	`hs_v2_date_entered_48119601` datetime,
	`hs_v2_date_entered_current_stage` datetime,
	`hs_v2_date_entered_customer` datetime,
	`hs_v2_date_entered_evangelist` datetime,
	`hs_v2_date_entered_lead` datetime,
	`hs_v2_date_entered_marketingqualifiedlead` datetime,
	`hs_v2_date_entered_opportunity` datetime,
	`hs_v2_date_entered_other` datetime,
	`hs_v2_date_entered_salesqualifiedlead` datetime,
	`hs_v2_date_entered_subscriber` datetime,
	`hs_v2_date_exited_123317274` datetime,
	`hs_v2_date_exited_1334400296` datetime,
	`hs_v2_date_exited_1334454586` datetime,
	`hs_v2_date_exited_48119601` datetime,
	`hs_v2_date_exited_customer` datetime,
	`hs_v2_date_exited_evangelist` datetime,
	`hs_v2_date_exited_lead` datetime,
	`hs_v2_date_exited_marketingqualifiedlead` datetime,
	`hs_v2_date_exited_opportunity` datetime,
	`hs_v2_date_exited_other` datetime,
	`hs_v2_date_exited_salesqualifiedlead` datetime,
	`hs_v2_date_exited_subscriber` datetime,
	`hs_v2_latest_time_in_123317274` decimal(20,6),
	`hs_v2_latest_time_in_1334400296` decimal(20,6),
	`hs_v2_latest_time_in_1334454586` decimal(20,6),
	`hs_v2_latest_time_in_48119601` decimal(20,6),
	`hs_v2_latest_time_in_customer` decimal(20,6),
	`hs_v2_latest_time_in_evangelist` decimal(20,6),
	`hs_v2_latest_time_in_lead` decimal(20,6),
	`hs_v2_latest_time_in_marketingqualifiedlead` decimal(20,6),
	`hs_v2_latest_time_in_opportunity` decimal(20,6),
	`hs_v2_latest_time_in_other` decimal(20,6),
	`hs_v2_latest_time_in_salesqualifiedlead` decimal(20,6),
	`hs_v2_latest_time_in_subscriber` decimal(20,6),
	`hs_v2_time_in_current_stage` datetime,
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`hubspotscore` decimal(20,6),
	`industry` text,
	`is_public` boolean,
	`ja_oferece_alguma_solucao_de_seguranca_` text,
	`lifecyclestage` text,
	`linkedin_company_page` text,
	`linkedinbio` text,
	`mkt_campaign_advice` text,
	`mkt_campaign_channels` text,
	`mkt_campaign_end_date` date,
	`mkt_campaign_start_date` date,
	`mkt_campaign_type` text,
	`name` text,
	`notes_last_contacted` datetime,
	`notes_last_updated` datetime,
	`notes_next_activity_date` datetime,
	`num_associated_contacts` decimal(20,6),
	`num_associated_deals` decimal(20,6),
	`num_contacted_notes` decimal(20,6),
	`num_conversion_events` decimal(20,6),
	`num_conversion_events_cardinality_sum_d095f14b` decimal(20,6),
	`num_notes` decimal(20,6),
	`numberofemployees` decimal(20,6),
	`other_partnership_companies` text,
	`other_partnership_vendors` text,
	`other_security_services_offer` text,
	`owneremail` text,
	`ownername` text,
	`partner_msp` text,
	`partner_msp_level` text,
	`partner_reseller` text,
	`partner_score` text,
	`phone` text,
	`quais_sao_as_linguagens_e_versoes_utilizadas_nestas_aplicacoes_` text,
	`qual_a_quantidade_de_equipamentos_gerenciados_por_sua_empresa_` text,
	`quantas_aplicacoes_serao_analisadas_pela_plataforma_e_qu_c2c458` text,
	`quantas_contas_em_clouds___aws__azure__gcp_etc__` text,
	`quantidade_de_clientes_atendidos_por_sua_empresa` text,
	`quantos_colaboradores_sua_empresa_tem_` text,
	`rainforest_programs` text,
	`recent_conversion_date` datetime,
	`recent_conversion_date_timestamp_latest_value_72856da1` datetime,
	`recent_conversion_event_name` text,
	`recent_conversion_event_name_timestamp_latest_value_66c820bf` datetime,
	`recent_deal_amount` decimal(20,6),
	`recent_deal_close_date` datetime,
	`registration_number` decimal(20,6),
	`sales_history` text,
	`sales_region` text,
	`se_sim__qual_a_composicao_de_ferramentas_da_esteira_ci_cd_` text,
	`select_country` text,
	`source` text,
	`state` text,
	`state_br` text,
	`state_or_region` text,
	`timezone` text,
	`total_money_raised` text,
	`total_revenue` decimal(20,6),
	`twitterbio` text,
	`twitterfollowers` decimal(20,6),
	`twitterhandle` text,
	`type` text,
	`visited_pages` text,
	`web_technologies` text,
	`website` text,
	`zip` text,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`),
	CONSTRAINT `companies_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`address` text,
	`amount_of_assets` decimal(20,6),
	`app` text,
	`associated_company_has_open_deal` text,
	`associatedcompanyid` decimal(20,6),
	`campaign_score` text,
	`certificate_rainforest` text,
	`city` text,
	`closedate` datetime,
	`cloud` text,
	`company` text,
	`company_size` text,
	`contact_set_as_marketing` datetime,
	`contact_source` text,
	`controller__contact_owner_id` decimal(20,6),
	`controller__type` text,
	`controller_contact_client` text,
	`controller_contact_company_id` decimal(20,6),
	`controller_deal_renewal_id` text,
	`controller_deal_renewal_name` text,
	`controller_partner_contract_concluded_date` date,
	`country` text,
	`createdate` datetime,
	`currentlyinworkflow` text,
	`days_to_close` decimal(20,6),
	`do_you_expect_use_some_brand_intelligence_module_` text,
	`do_you_want_to_provide_information_related_to_security_s_b29631` text,
	`does_the_company_have_a_built_in_ci_cd_set_up_and_use_gi_2b1706` text,
	`email` text,
	`email_billing_contact` text,
	`email_technical_contact` text,
	`engagements_last_meeting_booked` datetime,
	`first_conversion_date` datetime,
	`first_conversion_event_name` text,
	`first_deal_created_date` datetime,
	`firstname` text,
	`fraud` text,
	`full_name` text,
	`how_many_applications_will_be_analyzed_by_the_platform_a_ce6ffa` decimal(20,6),
	`hs_additional_emails` text,
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_contact_vids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_analytics_average_page_views` decimal(20,6),
	`hs_analytics_first_referrer` text,
	`hs_analytics_first_timestamp` datetime,
	`hs_analytics_first_url` text,
	`hs_analytics_first_visit_timestamp` datetime,
	`hs_analytics_last_referrer` text,
	`hs_analytics_last_timestamp` datetime,
	`hs_analytics_last_touch_converting_campaign` text,
	`hs_analytics_last_url` text,
	`hs_analytics_last_visit_timestamp` datetime,
	`hs_analytics_num_event_completions` decimal(20,6),
	`hs_analytics_num_page_views` decimal(20,6),
	`hs_analytics_num_visits` decimal(20,6),
	`hs_analytics_revenue` decimal(20,6),
	`hs_analytics_source` text,
	`hs_analytics_source_data_1` text,
	`hs_analytics_source_data_2` text,
	`hs_associated_target_accounts` decimal(20,6),
	`hs_calculated_form_submissions` text,
	`hs_calculated_mobile_number` text,
	`hs_calculated_phone_number` text,
	`hs_calculated_phone_number_country_code` text,
	`hs_content_membership_email` text,
	`hs_content_membership_follow_up_enqueued_at` datetime,
	`hs_content_membership_registered_at` datetime,
	`hs_content_membership_registration_domain_sent_to` text,
	`hs_content_membership_registration_email_sent_at` datetime,
	`hs_content_membership_status` text,
	`hs_count_is_unworked` decimal(20,6),
	`hs_count_is_worked` decimal(20,6),
	`hs_created_by_user_id` decimal(20,6),
	`hs_currently_enrolled_in_prospecting_agent` boolean,
	`hs_email_bounce` decimal(20,6),
	`hs_email_click` decimal(20,6),
	`hs_email_delivered` decimal(20,6),
	`hs_email_domain` text,
	`hs_email_first_click_date` datetime,
	`hs_email_first_open_date` datetime,
	`hs_email_first_send_date` datetime,
	`hs_email_hard_bounce_reason_enum` text,
	`hs_email_last_click_date` datetime,
	`hs_email_last_email_name` text,
	`hs_email_last_open_date` datetime,
	`hs_email_last_send_date` datetime,
	`hs_email_open` decimal(20,6),
	`hs_email_optimal_send_day_of_week` text,
	`hs_email_optimal_send_time_of_day` text,
	`hs_email_optout` boolean,
	`hs_email_optout_43660914` text,
	`hs_email_optout_43781475` text,
	`hs_email_optout_44481451` text,
	`hs_email_optout_45317042` text,
	`hs_email_optout_46654666` text,
	`hs_email_optout_49058722` text,
	`hs_email_optout_61260235` text,
	`hs_email_optout_82929903` text,
	`hs_email_optout_92392682` text,
	`hs_email_sends_since_last_engagement` decimal(20,6),
	`hs_first_engagement_object_id` decimal(20,6),
	`hs_first_outreach_date` datetime,
	`hs_full_name_or_email` text,
	`hs_google_click_id` text,
	`hs_ip_timezone` text,
	`hs_is_contact` boolean,
	`hs_is_unworked` boolean,
	`hs_last_sales_activity_date` datetime,
	`hs_last_sales_activity_timestamp` datetime,
	`hs_last_sales_activity_type` text,
	`hs_latest_disqualified_lead_date` datetime,
	`hs_latest_meeting_activity` datetime,
	`hs_latest_open_lead_date` datetime,
	`hs_latest_sequence_ended_date` datetime,
	`hs_latest_sequence_enrolled` decimal(20,6),
	`hs_latest_sequence_enrolled_date` datetime,
	`hs_latest_sequence_finished_date` datetime,
	`hs_latest_sequence_unenrolled_date` datetime,
	`hs_latest_source` text,
	`hs_latest_source_data_1` text,
	`hs_latest_source_data_2` text,
	`hs_latest_source_timestamp` datetime,
	`hs_latitude` decimal(20,6),
	`hs_lead_status` text,
	`hs_legal_basis` text,
	`hs_linkedin_ad_clicked` text,
	`hs_linkedin_url` text,
	`hs_longitude` decimal(20,6),
	`hs_marketable_reason_id` text,
	`hs_marketable_reason_type` text,
	`hs_marketable_status` text,
	`hs_marketable_until_renewal` text,
	`hs_membership_has_accessed_private_content` decimal(20,6),
	`hs_membership_last_private_content_access_date` datetime,
	`hs_messaging_engagement_score` decimal(20,6),
	`hs_notes_last_activity` text,
	`hs_num_associated_open_deals` decimal(20,6),
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_owning_teams` text,
	`hs_pipeline` text,
	`hs_predictivecontactscore_v2` decimal(20,6),
	`hs_predictivescoringtier` text,
	`hs_prospecting_agent_actively_enrolled_count` decimal(20,6),
	`hs_prospecting_agent_total_enrolled_count` decimal(20,6),
	`hs_registered_member` decimal(20,6),
	`hs_registration_method` text,
	`hs_sa_first_engagement_date` datetime,
	`hs_sa_first_engagement_descr` text,
	`hs_sa_first_engagement_object_type` text,
	`hs_sales_email_last_clicked` datetime,
	`hs_sales_email_last_opened` datetime,
	`hs_sales_email_last_replied` datetime,
	`hs_searchable_calculated_international_mobile_number` text,
	`hs_searchable_calculated_international_phone_number` text,
	`hs_searchable_calculated_mobile_number` text,
	`hs_searchable_calculated_phone_number` text,
	`hs_sequences_actively_enrolled_count` decimal(20,6),
	`hs_sequences_enrolled_count` decimal(20,6),
	`hs_sequences_is_enrolled` boolean,
	`hs_social_facebook_clicks` decimal(20,6),
	`hs_social_google_plus_clicks` decimal(20,6),
	`hs_social_linkedin_clicks` decimal(20,6),
	`hs_social_num_broadcast_clicks` decimal(20,6),
	`hs_social_twitter_clicks` decimal(20,6),
	`hs_time_between_contact_creation_and_deal_close` decimal(20,6),
	`hs_time_between_contact_creation_and_deal_creation` decimal(20,6),
	`hs_time_to_first_engagement` decimal(20,6),
	`hs_time_to_move_from_lead_to_customer` decimal(20,6),
	`hs_time_to_move_from_opportunity_to_customer` decimal(20,6),
	`hs_timezone` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_recipients` text,
	`hs_user_ids_of_all_owners` text,
	`hs_v2_cumulative_time_in_123317274` decimal(20,6),
	`hs_v2_cumulative_time_in_48119601` decimal(20,6),
	`hs_v2_cumulative_time_in_customer` decimal(20,6),
	`hs_v2_cumulative_time_in_lead` decimal(20,6),
	`hs_v2_cumulative_time_in_opportunity` decimal(20,6),
	`hs_v2_date_entered_123317274` datetime,
	`hs_v2_date_entered_48119601` datetime,
	`hs_v2_date_entered_current_stage` datetime,
	`hs_v2_date_entered_customer` datetime,
	`hs_v2_date_entered_lead` datetime,
	`hs_v2_date_entered_opportunity` datetime,
	`hs_v2_date_entered_subscriber` datetime,
	`hs_v2_date_exited_123317274` datetime,
	`hs_v2_date_exited_48119601` datetime,
	`hs_v2_date_exited_customer` datetime,
	`hs_v2_date_exited_lead` datetime,
	`hs_v2_date_exited_opportunity` datetime,
	`hs_v2_latest_time_in_123317274` decimal(20,6),
	`hs_v2_latest_time_in_48119601` decimal(20,6),
	`hs_v2_latest_time_in_customer` decimal(20,6),
	`hs_v2_latest_time_in_lead` decimal(20,6),
	`hs_v2_latest_time_in_opportunity` decimal(20,6),
	`hs_v2_time_in_current_stage` datetime,
	`hs_was_imported` boolean,
	`hs_whatsapp_phone_number` text,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`hubspotscore` decimal(20,6),
	`icp_fit` text,
	`industry` text,
	`inform_number_of_brands` decimal(20,6),
	`inform_the_number_of_accounts__organizations__per_public_cloud` decimal(20,6),
	`infra__asset_` text,
	`initial_zoom_webinar_attendance_average_duration` decimal(20,6),
	`ip_city` text,
	`ip_country` text,
	`ip_country_code` text,
	`ip_state` text,
	`ip_state_code` text,
	`ip_zipcode` text,
	`ja_possui_iniciativa_de_desenvolvimento_seguro_` text,
	`jobtitle` text,
	`lastmodifieddate` datetime,
	`lastname` text,
	`leak` text,
	`lifecyclestage` text,
	`linkedin_profile_link` text,
	`linkedin_url` text,
	`linkedinbio` text,
	`mobile_phone_billing_contact` decimal(20,6),
	`mobile_phone_technical_contact` decimal(20,6),
	`mobilephone` text,
	`name_billing_contact` text,
	`name_technical_contact` text,
	`nda_become_a_partner` text,
	`notes_last_contacted` datetime,
	`notes_last_updated` datetime,
	`num_associated_deals` decimal(20,6),
	`num_contacted_notes` decimal(20,6),
	`num_conversion_events` decimal(20,6),
	`num_notes` decimal(20,6),
	`num_unique_conversion_events` decimal(20,6),
	`of_these_applications__how_many_are_microservices_` decimal(20,6),
	`partner_lead__company_name` text,
	`partner_lead__contact_type` text,
	`partner_lead__e_mail_address` text,
	`partner_lead__first_name` text,
	`partner_lead__last_name` text,
	`partner_lead__phone` decimal(20,6),
	`partner_lead__website_url` text,
	`phone` text,
	`portal_partner_user_role` text,
	`ptype` text,
	`quantity_devs_by_app` decimal(20,6),
	`recent_conversion_date` datetime,
	`recent_conversion_event_name` text,
	`recent_deal_amount` decimal(20,6),
	`recent_deal_close_date` datetime,
	`referral_code` text,
	`role_position` text,
	`score_icp` text,
	`select_country___` text,
	`sizing_inform_number_of_keywords` decimal(20,6),
	`sizing_inform_number_of_root_domains` decimal(20,6),
	`sizing_number_of_incident_handling_such_as_takedowns_per_year` decimal(20,6),
	`state` text,
	`states_br` text,
	`total_revenue` decimal(20,6),
	`type_sizing` text,
	`us_campaign_problem` text,
	`us_campaign_solution` text,
	`us_campaign_tier` text,
	`us_event_location` text,
	`us_event_source` text,
	`utm_medium` text,
	`utm_source` text,
	`visited_book_a_demo_page_3x` decimal(20,6),
	`visited_book_a_demo_page_3x_threshold` text,
	`what_are_the_languages_and_versions_used_in_these_applications_` text,
	`what_is_the_frequency_of_vulnerability_analysis_` text,
	`zip` text,
	`zoom_webinar_attendance_average_duration` decimal(20,6),
	`zoom_webinar_attendance_count` decimal(20,6),
	`zoom_webinar_joinlink` text,
	`zoom_webinar_registration_count` decimal(20,6),
	`website` text,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`),
	CONSTRAINT `contacts_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `credit_memo_applications` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`invoice_id` varchar(36) NOT NULL,
	`credit_memo_id` varchar(36) NOT NULL,
	`amount` decimal(20,6) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `credit_memo_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deals` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`created_by_user_id` varchar(36),
	`additional_discount` decimal(20,6),
	`amount` decimal(20,6),
	`amount_in_home_currency` decimal(20,6),
	`amount_of_assets` decimal(20,6),
	`app` text,
	`applications_modules_will_be_analyzed` decimal(20,6),
	`approval_date` date,
	`approve_partner_renewal` text,
	`authority` text,
	`authority_name` text,
	`billing_frequency` text,
	`budget_amount` decimal(20,6),
	`budget_confirmed` text,
	`business_competitors` text,
	`business_strategy` text,
	`clear_terms_and_conditions` text,
	`closed_lost_reason` text,
	`closed_won_reason` text,
	`closedate` datetime,
	`cloud` text,
	`comments` text,
	`committed_period_partner_discount_list` text,
	`consider_support_service` text,
	`contract_length` text,
	`controller__deal_actions` text,
	`controller__quote_automatically_created` text,
	`controller_commission_percentage_to_apply` decimal(20,6),
	`controller_company_id` text,
	`controller_contact_partner_associated` text,
	`controller_days_to_expire` decimal(20,6),
	`controller_deal_name` text,
	`controller_deal_owner_name` text,
	`controller_deal_source` text,
	`controller_deal_updates` text,
	`controller_highly_discounted_deals` text,
	`controller_number_of_calls` decimal(20,6),
	`controller_number_of_emails` decimal(20,6),
	`controller_number_of_whatsapp_message` decimal(20,6),
	`controller_quote_signed_id` text,
	`controller_renewal_process_steps` text,
	`controller_resale_company_name` text,
	`controller_sizing_sent` text,
	`createdate` datetime,
	`days_to_close` decimal(20,6),
	`days_waiting_approval` decimal(20,6),
	`deal_age` decimal(20,6),
	`deal_currency_code` text,
	`deal_partner_type` text,
	`deal_probability_commission_percentage` decimal(20,6),
	`deal_probability_percentage` decimal(20,6),
	`deal_registration_hubspot_shared_selling` text,
	`deal_registration_most_likely_hubspot_product_s_` text,
	`deal_score` decimal(20,6),
	`deal_score_engagement` decimal(20,6),
	`deal_score_fit` decimal(20,6),
	`deal_score_threshold` text,
	`dealname` text,
	`dealstage` text,
	`dealtype` text,
	`decline_reasons` text,
	`defined_contracting_model` text,
	`description` text,
	`engagements_last_meeting_booked` datetime,
	`engagements_last_meeting_booked_campaign` text,
	`engagements_last_meeting_booked_medium` text,
	`engagements_last_meeting_booked_source` text,
	`expect_use_brand` text,
	`expected_closing` text,
	`expiration_date` date,
	`fraud` text,
	`frequency_vulnerability_analysis` text,
	`government_deal` text,
	`have_ci_cd_git` text,
	`how_did_we_get_in` text,
	`how_many_developers_associated` decimal(20,6),
	`how_many_squads` text,
	`hs_actual_duration` decimal(20,6),
	`hs_acv` decimal(20,6),
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_collaborator_owner_ids` text,
	`hs_all_deal_split_owner_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_analytics_latest_source` text,
	`hs_analytics_latest_source_company` text,
	`hs_analytics_latest_source_contact` text,
	`hs_analytics_latest_source_data_1` text,
	`hs_analytics_latest_source_data_1_company` text,
	`hs_analytics_latest_source_data_1_contact` text,
	`hs_analytics_latest_source_data_2` text,
	`hs_analytics_latest_source_data_2_company` text,
	`hs_analytics_latest_source_data_2_contact` text,
	`hs_analytics_latest_source_timestamp` datetime,
	`hs_analytics_latest_source_timestamp_company` datetime,
	`hs_analytics_latest_source_timestamp_contact` datetime,
	`hs_analytics_source` text,
	`hs_analytics_source_data_1` text,
	`hs_analytics_source_data_2` text,
	`hs_arr` decimal(20,6),
	`hs_associated_deal_registration_deal_type` text,
	`hs_associated_deal_registration_product_interests` text,
	`hs_attributed_team_ids` text,
	`hs_average_call_duration` decimal(20,6),
	`hs_average_deal_owner_duration_in_current_stage` decimal(20,6),
	`hs_campaign` text,
	`hs_closed_amount` decimal(20,6),
	`hs_closed_amount_in_home_currency` decimal(20,6),
	`hs_closed_deal_close_date` decimal(20,6),
	`hs_closed_deal_create_date` decimal(20,6),
	`hs_closed_won_count` decimal(20,6),
	`hs_closed_won_date` datetime,
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_cross_account_note` text,
	`hs_cross_sell_opportunity` boolean,
	`hs_days_to_close_raw` decimal(20,6),
	`hs_deal_amount_calculation_preference` text,
	`hs_deal_registration_mrr` decimal(20,6),
	`hs_deal_registration_mrr_currency_code` text,
	`hs_deal_score` decimal(20,6),
	`hs_deal_stage_probability` decimal(20,6),
	`hs_deal_stage_probability_shadow` decimal(20,6),
	`hs_exchange_rate` decimal(20,6),
	`hs_forecast_amount` decimal(20,6),
	`hs_forecast_probability` decimal(20,6),
	`hs_form_id` text,
	`hs_has_empty_conditional_stage_properties` boolean,
	`hs_has_last_conversation_follow_ups` boolean,
	`hs_has_last_meeting_followups` boolean,
	`hs_is_active_shared_deal` boolean,
	`hs_is_closed` boolean,
	`hs_is_closed_count` decimal(20,6),
	`hs_is_closed_lost` boolean,
	`hs_is_closed_won` boolean,
	`hs_is_deal_split` boolean,
	`hs_is_in_first_deal_stage` boolean,
	`hs_is_open_count` decimal(20,6),
	`hs_is_stalled` boolean,
	`hs_is_stalled_after_timestamp` datetime,
	`hs_last_call_id_with_followups` decimal(20,6),
	`hs_last_conversation_with_followups_object_coordinates` text,
	`hs_last_gs_shared_message` datetime,
	`hs_last_meeting_id_with_followups` decimal(20,6),
	`hs_last_partner_shared_message_date` date,
	`hs_last_shared_message_create_date` datetime,
	`hs_lastmodifieddate` datetime,
	`hs_latest_approval_status` text,
	`hs_latest_approval_status_approval_id` decimal(20,6),
	`hs_latest_marketing_email_click_date` datetime,
	`hs_latest_marketing_email_open_date` datetime,
	`hs_latest_marketing_email_reply_date` datetime,
	`hs_latest_meeting_activity` datetime,
	`hs_latest_sales_email_click_date` datetime,
	`hs_latest_sales_email_open_date` datetime,
	`hs_latest_sales_email_reply_date` datetime,
	`hs_likelihood_to_close` decimal(20,6),
	`hs_line_item_global_term_hs_discount_percentage` text,
	`hs_line_item_global_term_hs_discount_percentage_enabled` boolean,
	`hs_line_item_global_term_hs_recurring_billing_period` text,
	`hs_line_item_global_term_hs_recurring_billing_period_enabled` boolean,
	`hs_line_item_global_term_hs_recurring_billing_start_date` text,
	`hs_line_item_global_term_hs_recurring_billing_start_date_84bd86` boolean,
	`hs_line_item_global_term_recurringbillingfrequency` text,
	`hs_line_item_global_term_recurringbillingfrequency_enabled` boolean,
	`hs_manual_campaign_ids` decimal(20,6),
	`hs_manual_forecast_category` text,
	`hs_merged_object_ids` text,
	`hs_mrr` decimal(20,6),
	`hs_net_pipeline_impact` decimal(20,6),
	`hs_next_meeting_id` decimal(20,6),
	`hs_next_meeting_name` text,
	`hs_next_meeting_start_time` datetime,
	`hs_next_step` text,
	`hs_next_step_updated_at` datetime,
	`hs_notes_last_activity` text,
	`hs_notes_next_activity` text,
	`hs_notes_next_activity_type` text,
	`hs_num_associated_active_deal_registrations` decimal(20,6),
	`hs_num_associated_deal_registrations` decimal(20,6),
	`hs_num_associated_deal_splits` decimal(20,6),
	`hs_num_of_associated_line_items` decimal(20,6),
	`hs_num_target_accounts` decimal(20,6),
	`hs_number_of_call_engagements` decimal(20,6),
	`hs_number_of_inbound_calls` decimal(20,6),
	`hs_number_of_outbound_calls` decimal(20,6),
	`hs_number_of_overdue_tasks` decimal(20,6),
	`hs_number_of_scheduled_meetings` decimal(20,6),
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_open_amount_in_home_currency` decimal(20,6),
	`hs_open_deal_create_date` decimal(20,6),
	`hs_owning_teams` text,
	`hs_partner_tech_win` text,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_predicted_amount` decimal(20,6),
	`hs_predicted_amount_in_home_currency` decimal(20,6),
	`hs_primary_associated_company` decimal(20,6),
	`hs_primary_quote_data_updated_at` datetime,
	`hs_priority` text,
	`hs_projected_amount` decimal(20,6),
	`hs_projected_amount_in_home_currency` decimal(20,6),
	`hs_read_only` boolean,
	`hs_sales_email_last_replied` datetime,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_source_object_id` decimal(20,6),
	`hs_submission_idempotent_id` text,
	`hs_synced_deal_owner_name_and_email` text,
	`hs_tag_ids` text,
	`hs_tcv` decimal(20,6),
	`hs_unique_creation_key` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_recipients` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_v2_cumulative_time_in_30187133` decimal(20,6),
	`hs_v2_cumulative_time_in_30187134` decimal(20,6),
	`hs_v2_cumulative_time_in_30187135` decimal(20,6),
	`hs_v2_cumulative_time_in_30187136` decimal(20,6),
	`hs_v2_cumulative_time_in_30187137` decimal(20,6),
	`hs_v2_cumulative_time_in_30187138` decimal(20,6),
	`hs_v2_cumulative_time_in_30187139` decimal(20,6),
	`hs_v2_cumulative_time_in_30537256` decimal(20,6),
	`hs_v2_cumulative_time_in_47747647` decimal(20,6),
	`hs_v2_cumulative_time_in_47747648` decimal(20,6),
	`hs_v2_cumulative_time_in_47747650` decimal(20,6),
	`hs_v2_cumulative_time_in_47747651` decimal(20,6),
	`hs_v2_cumulative_time_in_49950263` decimal(20,6),
	`hs_v2_cumulative_time_in_49950264` decimal(20,6),
	`hs_v2_cumulative_time_in_49950265` decimal(20,6),
	`hs_v2_cumulative_time_in_49950266` decimal(20,6),
	`hs_v2_cumulative_time_in_49950267` decimal(20,6),
	`hs_v2_cumulative_time_in_49950268` decimal(20,6),
	`hs_v2_cumulative_time_in_49950269` decimal(20,6),
	`hs_v2_cumulative_time_in_49991848` decimal(20,6),
	`hs_v2_date_entered_30187133` datetime,
	`hs_v2_date_entered_30187134` datetime,
	`hs_v2_date_entered_30187135` datetime,
	`hs_v2_date_entered_30187136` datetime,
	`hs_v2_date_entered_30187137` datetime,
	`hs_v2_date_entered_30187138` datetime,
	`hs_v2_date_entered_30187139` datetime,
	`hs_v2_date_entered_30537256` datetime,
	`hs_v2_date_entered_47747647` datetime,
	`hs_v2_date_entered_47747648` datetime,
	`hs_v2_date_entered_47747650` datetime,
	`hs_v2_date_entered_47747651` datetime,
	`hs_v2_date_entered_49950263` datetime,
	`hs_v2_date_entered_49950264` datetime,
	`hs_v2_date_entered_49950265` datetime,
	`hs_v2_date_entered_49950266` datetime,
	`hs_v2_date_entered_49950267` datetime,
	`hs_v2_date_entered_49950268` datetime,
	`hs_v2_date_entered_49950269` datetime,
	`hs_v2_date_entered_49991848` datetime,
	`hs_v2_date_entered_current_stage` datetime,
	`hs_v2_date_exited_30187133` datetime,
	`hs_v2_date_exited_30187134` datetime,
	`hs_v2_date_exited_30187135` datetime,
	`hs_v2_date_exited_30187136` datetime,
	`hs_v2_date_exited_30187137` datetime,
	`hs_v2_date_exited_30187138` datetime,
	`hs_v2_date_exited_30187139` datetime,
	`hs_v2_date_exited_30537256` datetime,
	`hs_v2_date_exited_47747647` datetime,
	`hs_v2_date_exited_47747648` datetime,
	`hs_v2_date_exited_47747650` datetime,
	`hs_v2_date_exited_47747651` datetime,
	`hs_v2_date_exited_49950263` datetime,
	`hs_v2_date_exited_49950264` datetime,
	`hs_v2_date_exited_49950265` datetime,
	`hs_v2_date_exited_49950266` datetime,
	`hs_v2_date_exited_49950267` datetime,
	`hs_v2_date_exited_49950268` datetime,
	`hs_v2_date_exited_49950269` datetime,
	`hs_v2_date_exited_49991848` datetime,
	`hs_v2_latest_time_in_30187133` decimal(20,6),
	`hs_v2_latest_time_in_30187134` decimal(20,6),
	`hs_v2_latest_time_in_30187135` decimal(20,6),
	`hs_v2_latest_time_in_30187136` decimal(20,6),
	`hs_v2_latest_time_in_30187137` decimal(20,6),
	`hs_v2_latest_time_in_30187138` decimal(20,6),
	`hs_v2_latest_time_in_30187139` decimal(20,6),
	`hs_v2_latest_time_in_30537256` decimal(20,6),
	`hs_v2_latest_time_in_47747647` decimal(20,6),
	`hs_v2_latest_time_in_47747648` decimal(20,6),
	`hs_v2_latest_time_in_47747650` decimal(20,6),
	`hs_v2_latest_time_in_47747651` decimal(20,6),
	`hs_v2_latest_time_in_49950263` decimal(20,6),
	`hs_v2_latest_time_in_49950264` decimal(20,6),
	`hs_v2_latest_time_in_49950265` decimal(20,6),
	`hs_v2_latest_time_in_49950266` decimal(20,6),
	`hs_v2_latest_time_in_49950267` decimal(20,6),
	`hs_v2_latest_time_in_49950268` decimal(20,6),
	`hs_v2_latest_time_in_49950269` decimal(20,6),
	`hs_v2_latest_time_in_49991848` decimal(20,6),
	`hs_v2_time_in_current_stage` datetime,
	`hs_was_imported` boolean,
	`hs_weighted_pipeline_in_company_currency` decimal(20,6),
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`identified_competitors` text,
	`identified_motivating_event` text,
	`identified_pain` text,
	`identified_products` text,
	`industry` text,
	`infra` text,
	`languages_and_versions_used` text,
	`leak` text,
	`location` text,
	`motivating_details` text,
	`notes_last_contacted` datetime,
	`notes_last_updated` datetime,
	`notes_next_activity_date` datetime,
	`num_associated_contacts` decimal(20,6),
	`num_contacted_notes` decimal(20,6),
	`num_notes` decimal(20,6),
	`number_brands` decimal(20,6),
	`number_incident` decimal(20,6),
	`number_keywords` decimal(20,6),
	`number_microservices` decimal(20,6),
	`number_of_accounts_organizations` decimal(20,6),
	`number_root_domains` decimal(20,6),
	`number_times_renewed` decimal(20,6),
	`offer_sent` text,
	`ok_executives__c_level_` text,
	`ok_project_sponsor` text,
	`ok_purchasing_sector` text,
	`ok_technical` text,
	`order_issued` text,
	`order_processed_in_rainforest` text,
	`other_competitor` text,
	`pain_details` text,
	`pipeline` text,
	`portal_partner__user_partner_id` decimal(20,6),
	`portal_partner_contact_user_name` text,
	`pov_required` text,
	`previous_deal_score_threshold` text,
	`process_already_defined_gmud` text,
	`provide_informationsecurity_services` text,
	`rainforest_modules` text,
	`realized_demo` text,
	`realized_poc` text,
	`realized_presentation` text,
	`renewal_date` datetime,
	`renewal_request_available_at` date,
	`roi_presented` text,
	`signed_quote_link` text,
	`sizing_confirmed` text,
	`special_price_request` text,
	`standard_architecture_programming_language` text,
	`term_months` decimal(20,6),
	`time_need_purchasing` date,
	`top_competitor_was` text,
	`what_happened_and_why_did_we_win` text,
	`won_reason` text,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`),
	CONSTRAINT `deals_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `dynamic_associations` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`from_object_type` varchar(150) NOT NULL,
	`from_hubspot_id` varchar(150) NOT NULL,
	`to_object_type` varchar(150) NOT NULL,
	`to_hubspot_id` varchar(150) NOT NULL,
	`association_label` varchar(150),
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `dynamic_associations_id` PRIMARY KEY(`id`),
	CONSTRAINT `uniq_dynamic_assoc` UNIQUE(`from_object_type`,`from_hubspot_id`,`to_object_type`,`to_hubspot_id`,`association_label`)
);
--> statement-breakpoint
CREATE TABLE `email_accounts` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`name` varchar(255) NOT NULL,
	`from_name` text,
	`from_email` text NOT NULL,
	`smtp_host` text NOT NULL,
	`smtp_port` int NOT NULL DEFAULT 587,
	`smtp_user` text NOT NULL,
	`smtp_password_encrypted` text NOT NULL,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `email_accounts_id` PRIMARY KEY(`id`),
	CONSTRAINT `email_accounts_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `email_activity_sync_state` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`last_processed_modified_at` datetime,
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `email_activity_sync_state_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `email_feature_settings` (
	`feature` varchar(50) NOT NULL,
	`email_account_id` varchar(36),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `email_feature_settings_feature` PRIMARY KEY(`feature`)
);
--> statement-breakpoint
CREATE TABLE `email_templates` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`name` text NOT NULL,
	`subject` text NOT NULL,
	`html_body` text NOT NULL DEFAULT (''),
	`objects` json NOT NULL DEFAULT ('[]'),
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `email_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `google_storage_settings` (
	`id` varchar(20) NOT NULL DEFAULT 'default',
	`project_id` text,
	`public_bucket` text,
	`private_bucket` text,
	`public_url` text,
	`service_account_key_encrypted` text,
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `google_storage_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_facsimile_thread_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_all_transactions_fee_name` text,
	`hs_all_transactions_fee_percentage` decimal(20,6),
	`hs_allow_partial_payments` boolean,
	`hs_allowed_checkout_fee_ids` text,
	`hs_allowed_commerce_payment_methods` text,
	`hs_allowed_payment_methods` text,
	`hs_amount_billed` decimal(20,6),
	`hs_amount_billed_in_company_currency` decimal(20,6),
	`hs_amount_billed_pre_tax` decimal(20,6),
	`hs_amount_paid` decimal(20,6),
	`hs_amount_paid_in_company_currency` decimal(20,6),
	`hs_amount_processing` decimal(20,6),
	`hs_associated_line_item_names` text,
	`hs_balance_due` decimal(20,6),
	`hs_balance_due_in_company_currency` decimal(20,6),
	`hs_billing_frequency_type` text,
	`hs_card_fee_name` text,
	`hs_card_fee_percentage` decimal(20,6),
	`hs_collect_address_types` text,
	`hs_comments` text,
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_credit_memo_applications` text,
	`hs_currency` text,
	`hs_custom_fields` text,
	`hs_data_sync_source_details` text,
	`hs_days_overdue` datetime,
	`hs_days_paid_late` text,
	`hs_direct_debit_fee_name` text,
	`hs_direct_debit_fee_percentage` decimal(20,6),
	`hs_discounts_total` decimal(20,6),
	`hs_domain` text,
	`hs_due_date` datetime,
	`hs_due_date_if_overdue` datetime,
	`hs_einvoice_status` text,
	`hs_enable_automated_taxes` boolean,
	`hs_exchange_rate` decimal(20,6),
	`hs_explainability_agent_enabled` boolean,
	`hs_external_account_id` text,
	`hs_external_contact_id` text,
	`hs_external_createdate` datetime,
	`hs_external_invoice_id` text,
	`hs_external_recipient` text,
	`hs_external_sync_error` text,
	`hs_fees_total` decimal(20,6),
	`hs_invoice_age_category` text,
	`hs_invoice_billable` boolean,
	`hs_invoice_class` text,
	`hs_invoice_date` datetime,
	`hs_invoice_latest_company_name` text,
	`hs_invoice_latest_contact_email` text,
	`hs_invoice_latest_contact_firstname` text,
	`hs_invoice_latest_contact_lastname` text,
	`hs_invoice_link` text,
	`hs_invoice_payment_collection_method` text,
	`hs_invoice_preset_id` decimal(20,6),
	`hs_invoice_source` text,
	`hs_invoice_status` text,
	`hs_invoice_status_details` text,
	`hs_invoice_tool_source` text,
	`hs_invoice_tool_source_id` text,
	`hs_language` text,
	`hs_last_edit_date` datetime,
	`hs_last_prioritized_date` datetime,
	`hs_last_reminder_sent_date` datetime,
	`hs_last_sent_date` datetime,
	`hs_lastmodifieddate` datetime,
	`hs_latest_content_prerendered_time` text,
	`hs_locale` text,
	`hs_merged_object_ids` text,
	`hs_net_payment_term` decimal(20,6),
	`hs_number` text,
	`hs_number_of_associated_subscriptions` decimal(20,6),
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_order_level_discounts_total` decimal(20,6),
	`hs_owning_teams` text,
	`hs_payment_collection_option` text,
	`hs_payment_date` datetime,
	`hs_payment_plan_status` text,
	`hs_payment_status` text,
	`hs_pdf_download_link` text,
	`hs_pdf_generation_status` text,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_purchase_order_number` text,
	`hs_read_only` boolean,
	`hs_received_by_recipient_date` datetime,
	`hs_recipient_company_address` text,
	`hs_recipient_company_address2` text,
	`hs_recipient_company_city` text,
	`hs_recipient_company_country` text,
	`hs_recipient_company_country_code` text,
	`hs_recipient_company_state` text,
	`hs_recipient_company_zip` text,
	`hs_recipient_shipping_address` text,
	`hs_recipient_shipping_address2` text,
	`hs_recipient_shipping_city` text,
	`hs_recipient_shipping_country` text,
	`hs_recipient_shipping_country_code` text,
	`hs_recipient_shipping_name` text,
	`hs_recipient_shipping_state` text,
	`hs_recipient_shipping_zip` text,
	`hs_sender_company_address` text,
	`hs_sender_company_address2` text,
	`hs_sender_company_city` text,
	`hs_sender_company_country` text,
	`hs_sender_company_domain` text,
	`hs_sender_company_logo_url` text,
	`hs_sender_company_name` text,
	`hs_sender_company_state` text,
	`hs_sender_company_zip` text,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_slug` text,
	`hs_status` text,
	`hs_store_payment_method_at_checkout` boolean,
	`hs_subtotal` decimal(20,6),
	`hs_tax_calculation_id` text,
	`hs_tax_id` text,
	`hs_taxes_total` decimal(20,6),
	`hs_test_mode` text,
	`hs_timezone` text,
	`hs_title` text,
	`hs_unique_creation_key` text,
	`hs_unique_id` text,
	`hs_upcoming_reminder_dates` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`invoice_actions` text,
	`msp_level` text,
	`receipt` text,
	`sent_date` date,
	`tenant` text,
	`type` text,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `invoice_discounts` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`invoice_id` varchar(36) NOT NULL,
	`name` text NOT NULL,
	`kind` varchar(20) NOT NULL,
	`value` decimal(20,6) NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `invoice_discounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kb_articles` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`category_id` varchar(36) NOT NULL,
	`subcategory_id` varchar(36) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`language` varchar(5) NOT NULL DEFAULT 'en',
	`title` text NOT NULL,
	`subtitle` text,
	`content` text NOT NULL DEFAULT (''),
	`visibility` varchar(20) NOT NULL DEFAULT 'internal',
	`status` varchar(20) NOT NULL DEFAULT 'draft',
	`translation_group_id` varchar(36),
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `kb_articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `kb_articles_subcat_slug_lang_unique` UNIQUE(`subcategory_id`,`slug`,`language`)
);
--> statement-breakpoint
CREATE TABLE `kb_categories` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`slug` varchar(255) NOT NULL,
	`title` text NOT NULL,
	`translations` json,
	`description` text,
	`image_url` text,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `kb_categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `kb_categories_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `kb_subcategories` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`category_id` varchar(36) NOT NULL,
	`slug` text NOT NULL,
	`title` text NOT NULL,
	`translations` json,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `kb_subcategories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `licenses` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`activation_date` datetime,
	`controller_company_id` text,
	`controller_partner_id` text,
	`controller_rf_license_id` text,
	`customer_name` text,
	`expiration_date` datetime,
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_lastmodifieddate` datetime,
	`hs_merged_object_ids` text,
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_owning_teams` text,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_read_only` boolean,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_unique_creation_key` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`license_group` text,
	`module` text,
	`name` text,
	`partner_name` text,
	`platform_created_date` datetime,
	`quantity` decimal(20,6),
	`revoke_date` date,
	`status` text,
	`subscription` text,
	`type` text,
	CONSTRAINT `licenses_id` PRIMARY KEY(`id`),
	CONSTRAINT `licenses_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `lifecycle_stages` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`object_type` varchar(30) NOT NULL,
	`external_name` text NOT NULL,
	`internal_name` varchar(255) NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `lifecycle_stages_id` PRIMARY KEY(`id`),
	CONSTRAINT `lifecycle_stages_object_type_internal_name_unique` UNIQUE(`object_type`,`internal_name`)
);
--> statement-breakpoint
CREATE TABLE `line_items` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`amount` decimal(20,6),
	`available_external` boolean,
	`controller_account_manager` text,
	`controller_deal_closed_date` datetime,
	`controller_deal_created_date` datetime,
	`controller_deal_name` text,
	`controller_license_created_date` date,
	`controller_line_item_amount_paid` decimal(20,6),
	`controller_line_item_billing_frequency` text,
	`controller_line_item_billing_type` text,
	`controller_line_item_contract_term` text,
	`controller_line_item_created_date` date,
	`controller_line_item_payment_date` date,
	`controller_line_item_percentage_commission` decimal(20,6),
	`controller_main_name` text,
	`controller_original_quantity` decimal(20,6),
	`controller_total_license_units` decimal(20,6),
	`controller_unit_price` decimal(20,6),
	`createdate` datetime,
	`customer_name` text,
	`description` text,
	`discount` decimal(20,6),
	`discount_type` text,
	`group_license` text,
	`hs_acv` decimal(20,6),
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_allow_buyer_selected_quantity` text,
	`hs_arr` decimal(20,6),
	`hs_auto_tax_amount` decimal(20,6),
	`hs_billing_cycle_anchor_date` date,
	`hs_billing_period_end_date` date,
	`hs_billing_period_start_date` date,
	`hs_billing_start_delay_days` decimal(20,6),
	`hs_billing_start_delay_months` decimal(20,6),
	`hs_billing_start_delay_type` text,
	`hs_bundle_id` decimal(20,6),
	`hs_buyer_selected_quantity_max` decimal(20,6),
	`hs_buyer_selected_quantity_min` decimal(20,6),
	`hs_cost_of_goods_sold` decimal(20,6),
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_discount_percentage` decimal(20,6),
	`hs_effective_unit_price` decimal(20,6),
	`hs_exchange_rate` decimal(20,6),
	`hs_external_id` decimal(20,6),
	`hs_external_tax_rate_id` text,
	`hs_group_key` text,
	`hs_has_prorating_leading` boolean,
	`hs_has_prorating_trailing` boolean,
	`hs_images` text,
	`hs_is_editable_price` boolean,
	`hs_is_optional` boolean,
	`hs_is_parent` boolean,
	`hs_lastmodifieddate` datetime,
	`hs_line_item_currency_code` text,
	`hs_line_item_group_config_id` decimal(20,6),
	`hs_line_item_group_instance_key` text,
	`hs_locked` boolean,
	`hs_margin` decimal(20,6),
	`hs_margin_acv` decimal(20,6),
	`hs_margin_arr` decimal(20,6),
	`hs_margin_mrr` decimal(20,6),
	`hs_margin_tcv` decimal(20,6),
	`hs_merged_object_ids` text,
	`hs_mrr` decimal(20,6),
	`hs_num_child_line_items` decimal(20,6),
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_optional_metadata` text,
	`hs_origin_key` text,
	`hs_owning_teams` text,
	`hs_parent_line_item_id` decimal(20,6),
	`hs_parent_object_type_id` text,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_position_on_quote` decimal(20,6),
	`hs_post_tax_amount` decimal(20,6),
	`hs_pre_discount_amount` decimal(20,6),
	`hs_price_book_id` decimal(20,6),
	`hs_pricing_model` text,
	`hs_product_id` decimal(20,6),
	`hs_product_type` text,
	`hs_prorating_leading_amount` decimal(20,6),
	`hs_prorating_leading_end_date` date,
	`hs_prorating_leading_post_tax_amount` decimal(20,6),
	`hs_prorating_leading_scale` decimal(20,6),
	`hs_prorating_leading_start_date` date,
	`hs_prorating_leading_tax_amount` decimal(20,6),
	`hs_prorating_leading_term_length` text,
	`hs_prorating_scale` decimal(20,6),
	`hs_prorating_trailing_amount` decimal(20,6),
	`hs_prorating_trailing_end_date` date,
	`hs_prorating_trailing_post_tax_amount` decimal(20,6),
	`hs_prorating_trailing_scale` decimal(20,6),
	`hs_prorating_trailing_start_date` date,
	`hs_prorating_trailing_tax_amount` decimal(20,6),
	`hs_prorating_trailing_term_length` text,
	`hs_ramp_group_name` text,
	`hs_ramp_key` text,
	`hs_ramp_phase_name` text,
	`hs_read_only` boolean,
	`hs_recurring_billing_day_of_month` decimal(20,6),
	`hs_recurring_billing_end_date` date,
	`hs_recurring_billing_number_of_payments` decimal(20,6),
	`hs_recurring_billing_period` text,
	`hs_recurring_billing_start_date` date,
	`hs_recurring_billing_terms` text,
	`hs_rich_text_description` text,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_sku` text,
	`hs_sync_amount` decimal(20,6),
	`hs_tax_amount` decimal(20,6),
	`hs_tax_assessed` boolean,
	`hs_tax_calculation_id` text,
	`hs_tax_category` text,
	`hs_tax_label` text,
	`hs_tax_rate` decimal(20,6),
	`hs_tax_rate_group_id` text,
	`hs_tcv` decimal(20,6),
	`hs_term_in_months` decimal(20,6),
	`hs_tier_amount` decimal(20,6),
	`hs_tier_prices` text,
	`hs_tier_ranges` text,
	`hs_total_discount` decimal(20,6),
	`hs_unique_creation_key` text,
	`hs_unscaled_amount` decimal(20,6),
	`hs_unscaled_pre_discount_amount` decimal(20,6),
	`hs_unscaled_total_discount` decimal(20,6),
	`hs_updated_by_user_id` decimal(20,6),
	`hs_url` text,
	`hs_use_prorating` boolean,
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_variant_id` decimal(20,6),
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`module` text,
	`name` text,
	`price` decimal(20,6),
	`quantity` decimal(20,6),
	`recurringbillingfrequency` text,
	`tax` decimal(20,6),
	CONSTRAINT `line_items_id` PRIMARY KEY(`id`),
	CONSTRAINT `line_items_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `partnerships` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`address` text,
	`city` text,
	`close_date` date,
	`closed_lost_reason` text,
	`closed_note` text,
	`company_id` decimal(20,6),
	`company_name` text,
	`contract_concluded_date` date,
	`contract_signature_date` date,
	`controller__stages_numbers` decimal(20,6),
	`controller_current_partner_owner` text,
	`controller_origin` text,
	`country` text,
	`distributor` text,
	`email__billing_contact_` text,
	`email__technical_contact_` text,
	`exception_details` text,
	`full_name__billing_contact_` text,
	`full_name__technical_contact_` text,
	`have_you_double_checked_if_this_company_is_already_in_ra_21c679` text,
	`have_you_visited_the_contact_s_social_media___checking_p_6b7efe` text,
	`have_you_visited_the_partner_s_social_medias___checking__c9866c` text,
	`have_you_visited_the_partner_s_website___checking_partne_e4bc9e` text,
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_date_entered_1011557161` datetime,
	`hs_date_entered_155991196` datetime,
	`hs_date_entered_49994856` datetime,
	`hs_date_entered_49994857` datetime,
	`hs_date_entered_49994858` datetime,
	`hs_date_entered_49994859` datetime,
	`hs_date_entered_49994860` datetime,
	`hs_date_entered_49994861` datetime,
	`hs_date_entered_50005879` datetime,
	`hs_date_entered_50005880` datetime,
	`hs_date_entered_65227423` datetime,
	`hs_date_entered_72208550` datetime,
	`hs_date_exited_1011557161` datetime,
	`hs_date_exited_155991196` datetime,
	`hs_date_exited_49994856` datetime,
	`hs_date_exited_49994857` datetime,
	`hs_date_exited_49994858` datetime,
	`hs_date_exited_49994859` datetime,
	`hs_date_exited_49994860` datetime,
	`hs_date_exited_49994861` datetime,
	`hs_date_exited_50005879` datetime,
	`hs_date_exited_50005880` datetime,
	`hs_date_exited_65227423` datetime,
	`hs_date_exited_72208550` datetime,
	`hs_lastmodifieddate` datetime,
	`hs_merged_object_ids` text,
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_owning_teams` text,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_pipeline` text,
	`hs_pipeline_stage` text,
	`hs_read_only` boolean,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_tag_ids` text,
	`hs_time_in_1011557161` decimal(20,6),
	`hs_time_in_155991196` decimal(20,6),
	`hs_time_in_49994856` decimal(20,6),
	`hs_time_in_49994857` decimal(20,6),
	`hs_time_in_49994858` decimal(20,6),
	`hs_time_in_49994859` decimal(20,6),
	`hs_time_in_49994860` decimal(20,6),
	`hs_time_in_49994861` decimal(20,6),
	`hs_time_in_50005879` decimal(20,6),
	`hs_time_in_50005880` decimal(20,6),
	`hs_time_in_65227423` decimal(20,6),
	`hs_time_in_72208550` decimal(20,6),
	`hs_unique_creation_key` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_v2_date_entered_current_stage` datetime,
	`hs_v2_time_in_current_stage` datetime,
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`independent_consultants` text,
	`msp_level` text,
	`name` text,
	`note` text,
	`partnership_exception` text,
	`pov_required` text,
	`rainforest_partner_programs` text,
	`send_contract` text,
	`state` text,
	`submission_idempotent_id` text,
	`type` text,
	`zip_code` text,
	CONSTRAINT `partnerships_id` PRIMARY KEY(`id`),
	CONSTRAINT `partnerships_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `password_reset_tokens` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`user_id` varchar(36) NOT NULL,
	`token_hash` text NOT NULL,
	`expires_at` datetime NOT NULL,
	`used_at` datetime,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `password_reset_tokens_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_automated_collection_attempts` decimal(20,6),
	`hs_billing_address_city` text,
	`hs_billing_address_country` text,
	`hs_billing_address_line_1` text,
	`hs_billing_address_line_2` text,
	`hs_billing_address_state` text,
	`hs_billing_address_zip` text,
	`hs_billing_bill_to_name` text,
	`hs_charged_from_stored_payment_method` boolean,
	`hs_commerce_payment_method` text,
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_currency_code` text,
	`hs_customer_email` text,
	`hs_digital_wallet_type` text,
	`hs_dispute_amount` decimal(20,6),
	`hs_dispute_closed_date` datetime,
	`hs_dispute_create_date` datetime,
	`hs_dispute_deadline` datetime,
	`hs_dispute_reason` text,
	`hs_estimated_payout_date` date,
	`hs_external_payment_method_id` text,
	`hs_external_reference_id` text,
	`hs_fees_amount` decimal(20,6),
	`hs_fees_amount_in_portal_currency` decimal(20,6),
	`hs_fees_amount_in_settlement_currency` decimal(20,6),
	`hs_formatted_billing_address` text,
	`hs_formatted_shipping_address` text,
	`hs_has_associated_invoice` boolean,
	`hs_hubspot_payments_enabled` boolean,
	`hs_initial_amount` decimal(20,6),
	`hs_initial_amount_in_portal_currency` decimal(20,6),
	`hs_initial_amount_in_settlement_currency` decimal(20,6),
	`hs_initiated_date` datetime,
	`hs_internal_comment` text,
	`hs_internal_payment_id` decimal(20,6),
	`hs_is_refundable` boolean,
	`hs_lastmodifieddate` datetime,
	`hs_latest_refund_reason` text,
	`hs_latest_status` text,
	`hs_latest_status_updated_date` datetime,
	`hs_line_item_discounts_amount` decimal(20,6),
	`hs_line_item_discounts_amount_in_portal_currency` decimal(20,6),
	`hs_manual_payment_creation_context` text,
	`hs_max_refundable_amount` decimal(20,6),
	`hs_max_refundable_amount_in_portal_currency` decimal(20,6),
	`hs_merged_object_ids` text,
	`hs_net_amount` decimal(20,6),
	`hs_net_amount_after_refunds` decimal(20,6),
	`hs_net_amount_in_portal_currency` decimal(20,6),
	`hs_net_amount_in_settlement_currency` decimal(20,6),
	`hs_next_automated_collection_attempt` datetime,
	`hs_number_of_associated_invoices` decimal(20,6),
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_order_discount_amount` decimal(20,6),
	`hs_order_discount_amount_in_portal_currency` decimal(20,6),
	`hs_order_discount_code` text,
	`hs_order_discount_percentage` decimal(20,6),
	`hs_order_discount_template_id` decimal(20,6),
	`hs_owning_teams` text,
	`hs_payment_creation_method` text,
	`hs_payment_id` text,
	`hs_payment_method` text,
	`hs_payment_method_bank_or_issuer` text,
	`hs_payment_method_id` decimal(20,6),
	`hs_payment_method_last_4` text,
	`hs_payment_method_type` text,
	`hs_payment_source_app` text,
	`hs_payment_source_id` text,
	`hs_payment_source_name` text,
	`hs_payment_source_url` text,
	`hs_payment_type` text,
	`hs_payout_date` datetime,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_platform_fee` decimal(20,6),
	`hs_platform_fee_in_portal_currency` decimal(20,6),
	`hs_platform_fee_in_settlement_currency` decimal(20,6),
	`hs_platform_invoice_id` decimal(20,6),
	`hs_platform_invoice_id_and_failed_at` text,
	`hs_platform_invoice_id_and_payment_method_id` text,
	`hs_presentment_to_portal_currency_dated_exchange_rate` decimal(20,6),
	`hs_presentment_to_settlement_currency_exchange_rate` decimal(20,6),
	`hs_processing_manual_collection_attempt` boolean,
	`hs_processor_type` text,
	`hs_read_only` boolean,
	`hs_reference_number` text,
	`hs_refund_deadline` datetime,
	`hs_refund_disabled_reason` text,
	`hs_refunds_amount` decimal(20,6),
	`hs_refunds_amount_in_portal_currency` decimal(20,6),
	`hs_refunds_amount_in_settlement_currency` decimal(20,6),
	`hs_remaining_manual_collection_attempts` decimal(20,6),
	`hs_retries_disabled_reason` text,
	`hs_settlement_currency_code` text,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_shipping_address_city` text,
	`hs_shipping_address_country` text,
	`hs_shipping_address_line_1` text,
	`hs_shipping_address_line_2` text,
	`hs_shipping_address_state` text,
	`hs_shipping_address_zip` text,
	`hs_shipping_ship_to_name` text,
	`hs_submission_conversion_id` text,
	`hs_total_collected_amount_after_refunds` decimal(20,6),
	`hs_total_collected_amount_after_refunds_in_portal_currency` decimal(20,6),
	`hs_total_collected_fees_amount` decimal(20,6),
	`hs_total_collected_fees_amount_in_portal_currency` decimal(20,6),
	`hs_total_collected_tax_amount` decimal(20,6),
	`hs_total_collected_tax_amount_in_portal_currency` decimal(20,6),
	`hs_total_discounts_amount` decimal(20,6),
	`hs_total_discounts_amount_in_portal_currency` decimal(20,6),
	`hs_unique_creation_key` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_was_created_with_associated_deal` text,
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`),
	CONSTRAINT `payments_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `permission_sets` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`name` varchar(255) NOT NULL,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `permission_sets_id` PRIMARY KEY(`id`),
	CONSTRAINT `permission_sets_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `permission_set_modules` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`permission_set_id` varchar(36) NOT NULL,
	`module` varchar(30) NOT NULL,
	`view_scope` varchar(10) NOT NULL DEFAULT 'none',
	`can_create` boolean NOT NULL DEFAULT false,
	`edit_scope` varchar(10) NOT NULL DEFAULT 'none',
	`delete_scope` varchar(10) NOT NULL DEFAULT 'none',
	`merge_scope` varchar(10) NOT NULL DEFAULT 'none',
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `permission_set_modules_id` PRIMARY KEY(`id`),
	CONSTRAINT `permission_set_modules_permission_set_id_module_unique` UNIQUE(`permission_set_id`,`module`)
);
--> statement-breakpoint
CREATE TABLE `pipelines` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`object_type` varchar(30) NOT NULL,
	`external_name` text NOT NULL,
	`internal_name` text NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `pipelines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pipeline_stages` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`pipeline_id` varchar(36) NOT NULL,
	`external_name` text NOT NULL,
	`internal_name` text NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `pipeline_stages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `processed_hubspot_emails` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`email_hubspot_id` varchar(255) NOT NULL,
	`activity_group_id` varchar(36) NOT NULL,
	`processed_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `processed_hubspot_emails_id` PRIMARY KEY(`id`),
	CONSTRAINT `processed_hubspot_emails_email_hubspot_id_unique` UNIQUE(`email_hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `processed_inbound_emails` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`support_inbox_id` varchar(36) NOT NULL,
	`message_id` varchar(255) NOT NULL,
	`ticket_id` varchar(36) NOT NULL,
	`processed_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `processed_inbound_emails_id` PRIMARY KEY(`id`),
	CONSTRAINT `processed_inbound_emails_support_inbox_id_message_id_unique` UNIQUE(`support_inbox_id`,`message_id`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64),
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`amount` decimal(20,6),
	`available_external` boolean,
	`controller_account_manager` text,
	`controller_deal_closed_date` datetime,
	`controller_deal_created_date` datetime,
	`controller_deal_name` text,
	`controller_license_created_date` date,
	`controller_line_item_amount_paid` decimal(20,6),
	`controller_line_item_billing_frequency` text,
	`controller_line_item_billing_type` text,
	`controller_line_item_contract_term` text,
	`controller_line_item_created_date` date,
	`controller_line_item_payment_date` date,
	`controller_line_item_percentage_commission` decimal(20,6),
	`controller_main_name` text,
	`controller_original_quantity` decimal(20,6),
	`controller_total_license_units` decimal(20,6),
	`controller_unit_price` decimal(20,6),
	`createdate` datetime,
	`description` text,
	`discount` decimal(20,6),
	`group_license` text,
	`hs_all_accessible_team_ids` text,
	`hs_all_assigned_business_unit_ids` text,
	`hs_all_owner_ids` text,
	`hs_all_team_ids` text,
	`hs_avatar_filemanager_key` text,
	`hs_bundle_grouping_config_id` decimal(20,6),
	`hs_bundle_type` text,
	`hs_cost_of_goods_sold` decimal(20,6),
	`hs_created_by_user_id` decimal(20,6),
	`hs_createdate` datetime,
	`hs_discount_percentage` decimal(20,6),
	`hs_folder` text,
	`hs_folder_id` decimal(20,6),
	`hs_folder_name` text,
	`hs_images` text,
	`hs_lastmodifieddate` datetime,
	`hs_merged_object_ids` text,
	`hs_object_id` decimal(20,6),
	`hs_object_source` text,
	`hs_object_source_detail_1` text,
	`hs_object_source_detail_2` text,
	`hs_object_source_detail_3` text,
	`hs_object_source_id` text,
	`hs_object_source_label` text,
	`hs_object_source_user_id` decimal(20,6),
	`hs_owning_teams` text,
	`hs_pinned_engagement_id` decimal(20,6),
	`hs_price_usd` decimal(20,6),
	`hs_pricing_model` text,
	`hs_product_bundle_supported_currencies` text,
	`hs_product_classification` text,
	`hs_product_supported_currencies` text,
	`hs_product_type` text,
	`hs_read_only` boolean,
	`hs_recurring_billing_period` text,
	`hs_recurring_billing_start_date` date,
	`hs_rich_text_description` text,
	`hs_shared_team_ids` text,
	`hs_shared_user_ids` text,
	`hs_sku` text,
	`hs_status` text,
	`hs_supported_currencies` text,
	`hs_tax_category` text,
	`hs_tier_prices` text,
	`hs_tier_ranges` text,
	`hs_unique_creation_key` text,
	`hs_updated_by_user_id` decimal(20,6),
	`hs_url` text,
	`hs_user_ids_of_all_notification_followers` text,
	`hs_user_ids_of_all_notification_unfollowers` text,
	`hs_user_ids_of_all_owners` text,
	`hs_was_imported` boolean,
	`hubspot_owner_assigneddate` datetime,
	`hubspot_owner_id` text,
	`hubspot_team_id` text,
	`module` text,
	`name` text,
	`price` decimal(20,6),
	`quantity` decimal(20,6),
	`recurringbillingfrequency` text,
	`tax` decimal(20,6),
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `quotes` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`hubspot_id` varchar(64) NOT NULL,
	`archived` boolean NOT NULL DEFAULT false,
	`raw_hubspot_payload` json,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`hs_title` text,
	`hs_quote_number` text,
	`hs_quote_status` text,
	`hs_quote_amount` decimal(20,6),
	`hs_tcv` decimal(20,6),
	`hs_currency` text,
	`hs_deal_name` text,
	`hs_expiration_date` datetime,
	`hs_last_published_date` datetime,
	`is_signed` boolean,
	`signed_date` datetime,
	`hubspot_owner_id` text,
	`hs_sender_firstname` text,
	`hs_sender_lastname` text,
	`hs_sender_jobtitle` text,
	`hs_sender_email` text,
	`hs_sender_phone` text,
	`hs_sender_company_name` text,
	`hs_comments` text,
	`hs_terms` text,
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotes_hubspot_id_unique` UNIQUE(`hubspot_id`)
);
--> statement-breakpoint
CREATE TABLE `quote_discounts` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`quote_id` varchar(36) NOT NULL,
	`name` text NOT NULL,
	`kind` varchar(20) NOT NULL,
	`value` decimal(20,6) NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `quote_discounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quote_settings` (
	`id` varchar(20) NOT NULL DEFAULT 'default',
	`default_expiration_days` int NOT NULL DEFAULT 30,
	`default_signer_user_id` varchar(36),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `quote_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quote_signers` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`quote_id` varchar(36) NOT NULL,
	`signer_type` varchar(20) NOT NULL,
	`contact_id` varchar(36),
	`user_id` varchar(36),
	`method` varchar(20) NOT NULL DEFAULT 'native',
	`signer_name` text NOT NULL,
	`signer_email` text,
	`token_hash` varchar(255),
	`token_expires_at` datetime,
	`signature_image` text,
	`ip_address` text,
	`user_agent` text,
	`sort_order` int NOT NULL DEFAULT 0,
	`signed_at` datetime,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `quote_signers_id` PRIMARY KEY(`id`),
	CONSTRAINT `quote_signers_token_hash_unique` UNIQUE(`token_hash`)
);
--> statement-breakpoint
CREATE TABLE `record_history` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`object_type` varchar(30) NOT NULL,
	`object_id` varchar(36) NOT NULL,
	`type` text NOT NULL DEFAULT ('system'),
	`title` text NOT NULL,
	`description` text,
	`user_id` varchar(36),
	`occurred_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`activity_group_id` varchar(36),
	CONSTRAINT `record_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reminder_log` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`object_type` varchar(30) NOT NULL,
	`object_id` varchar(36) NOT NULL,
	`rule_id` varchar(36) NOT NULL,
	`sent_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `reminder_log_id` PRIMARY KEY(`id`),
	CONSTRAINT `reminder_log_object_type_object_id_rule_id_unique` UNIQUE(`object_type`,`object_id`,`rule_id`)
);
--> statement-breakpoint
CREATE TABLE `reminder_rule` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`object_type` text NOT NULL,
	`label` text NOT NULL,
	`days_before_trigger` int NOT NULL,
	`subject_template` text,
	`body_template` text,
	`email_template_id` varchar(36),
	`enabled` boolean NOT NULL DEFAULT true,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `reminder_rule_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `snippets` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`name` text NOT NULL,
	`content` text NOT NULL DEFAULT (''),
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `snippets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `support_inboxes` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`name` varchar(255) NOT NULL,
	`imap_host` text NOT NULL,
	`imap_port` int NOT NULL DEFAULT 993,
	`imap_secure` boolean NOT NULL DEFAULT true,
	`imap_user` text NOT NULL,
	`auth_type` text NOT NULL DEFAULT ('password'),
	`imap_password_encrypted` text,
	`smtp_host` text,
	`smtp_port` int,
	`ms_tenant_id` text,
	`ms_client_id` text,
	`ms_client_secret_encrypted` text,
	`folder` text NOT NULL DEFAULT ('INBOX'),
	`pipeline_id` varchar(36) NOT NULL,
	`default_stage_id` varchar(36) NOT NULL,
	`last_uid` int NOT NULL DEFAULT 0,
	`enabled` boolean NOT NULL DEFAULT false,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `support_inboxes_id` PRIMARY KEY(`id`),
	CONSTRAINT `support_inboxes_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` varchar(36) NOT NULL DEFAULT (uuid()),
	`first_name` varchar(100) NOT NULL,
	`last_name` varchar(100) NOT NULL,
	`email` varchar(255) NOT NULL,
	`password_hash` varchar(255) NOT NULL,
	`role` varchar(50) NOT NULL DEFAULT 'admin',
	`account_type` varchar(20) NOT NULL DEFAULT 'internal',
	`company_id` varchar(36),
	`hubspot_owner_id` text,
	`permission_set_id` varchar(36),
	`job_title` text,
	`phone` text,
	`default_landing_page` text NOT NULL DEFAULT ('dashboard'),
	`avatar_key` text,
	`password_set_at` datetime,
	`created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
ALTER TABLE `email_feature_settings` ADD CONSTRAINT `email_feature_settings_email_account_id_email_accounts_id_fk` FOREIGN KEY (`email_account_id`) REFERENCES `email_accounts`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `kb_articles` ADD CONSTRAINT `kb_articles_category_id_kb_categories_id_fk` FOREIGN KEY (`category_id`) REFERENCES `kb_categories`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `kb_articles` ADD CONSTRAINT `kb_articles_subcategory_id_kb_subcategories_id_fk` FOREIGN KEY (`subcategory_id`) REFERENCES `kb_subcategories`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `kb_subcategories` ADD CONSTRAINT `kb_subcategories_category_id_kb_categories_id_fk` FOREIGN KEY (`category_id`) REFERENCES `kb_categories`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `password_reset_tokens` ADD CONSTRAINT `password_reset_tokens_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `permission_set_modules` ADD CONSTRAINT `permission_set_modules_permission_set_id_permission_sets_id_fk` FOREIGN KEY (`permission_set_id`) REFERENCES `permission_sets`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `pipeline_stages` ADD CONSTRAINT `pipeline_stages_pipeline_id_pipelines_id_fk` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `processed_inbound_emails` ADD CONSTRAINT `processed_inbound_emails_support_inbox_id_support_inboxes_id_fk` FOREIGN KEY (`support_inbox_id`) REFERENCES `support_inboxes`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `quote_settings` ADD CONSTRAINT `quote_settings_default_signer_user_id_users_id_fk` FOREIGN KEY (`default_signer_user_id`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `quote_signers` ADD CONSTRAINT `quote_signers_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `record_history` ADD CONSTRAINT `record_history_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `reminder_log` ADD CONSTRAINT `reminder_log_rule_id_reminder_rule_id_fk` FOREIGN KEY (`rule_id`) REFERENCES `reminder_rule`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `reminder_rule` ADD CONSTRAINT `reminder_rule_email_template_id_email_templates_id_fk` FOREIGN KEY (`email_template_id`) REFERENCES `email_templates`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `support_inboxes` ADD CONSTRAINT `support_inboxes_pipeline_id_pipelines_id_fk` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `support_inboxes` ADD CONSTRAINT `support_inboxes_default_stage_id_pipeline_stages_id_fk` FOREIGN KEY (`default_stage_id`) REFERENCES `pipeline_stages`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `users` ADD CONSTRAINT `users_permission_set_id_permission_sets_id_fk` FOREIGN KEY (`permission_set_id`) REFERENCES `permission_sets`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `kb_articles_category_id_idx` ON `kb_articles` (`category_id`);--> statement-breakpoint
CREATE INDEX `kb_articles_subcategory_id_idx` ON `kb_articles` (`subcategory_id`);--> statement-breakpoint
CREATE INDEX `kb_articles_translation_group_id_idx` ON `kb_articles` (`translation_group_id`);--> statement-breakpoint
CREATE INDEX `kb_subcategories_category_id_idx` ON `kb_subcategories` (`category_id`);--> statement-breakpoint
CREATE INDEX `pipelines_object_type_idx` ON `pipelines` (`object_type`);--> statement-breakpoint
CREATE INDEX `pipeline_stages_pipeline_id_idx` ON `pipeline_stages` (`pipeline_id`,`sort_order`);--> statement-breakpoint
CREATE INDEX `processed_inbound_emails_ticket_id_idx` ON `processed_inbound_emails` (`ticket_id`);--> statement-breakpoint
CREATE INDEX `quote_signers_quote_id_idx` ON `quote_signers` (`quote_id`);--> statement-breakpoint
CREATE INDEX `record_history_object_idx` ON `record_history` (`object_type`,`object_id`,`occurred_at`);